<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Fixtures/**/*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TLio.Json.SystemText\TLio.Json.SystemText.csproj" />
    <ProjectReference Include="..\TLio.Client\TLio.Client.csproj" />
    <ProjectReference Include="..\TLio.Extensions.Math\TLio.Extensions.Math.csproj" />
  </ItemGroup>

</Project>
