<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TLio.Json\TLio.Json.csproj" />
    <ProjectReference Include="..\..\TLio.Xml\TLio.Xml.csproj" />
    <ProjectReference Include="..\..\TLio.Yaml\TLio.Yaml.csproj" />
    <ProjectReference Include="..\..\TLio.Client\TLio.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Scripts/**/*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SampleInput/**/*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SampleInput/**/*.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SampleInput/**/*.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
