<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Fixtures/**/*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TLio.Core\TLio.Core.csproj" />
    <ProjectReference Include="..\TLio.Commands\TLio.Commands.csproj" />
    <ProjectReference Include="..\TLio.Functions\TLio.Functions.csproj" />
    <ProjectReference Include="..\TLio.Client\TLio.Client.csproj" />
    <ProjectReference Include="..\TLio.Json\TLio.Json.csproj" />
    <ProjectReference Include="..\TLio.Extensions.Math\TLio.Extensions.Math.csproj" />
    <ProjectReference Include="..\TLio.Extensions.Text\TLio.Extensions.Text.csproj" />
    <ProjectReference Include="..\TLio.Extensions.TimeDate\TLio.Extensions.TimeDate.csproj" />
    <ProjectReference Include="..\TLio.Extensions.ETL\TLio.Extensions.ETL.csproj" />
  </ItemGroup>

</Project>
