<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Fixtures/**/*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TLio.Core\TLio.Core.csproj" />
    <ProjectReference Include="..\TLio.Commands\TLio.Commands.csproj" />
    <ProjectReference Include="..\TLio.Functions\TLio.Functions.csproj" />
    <ProjectReference Include="..\TLio.Client\TLio.Client.csproj" />
    <ProjectReference Include="..\TLio.Json\TLio.Json.csproj" />
    <ProjectReference Include="..\TLio.Extensions.ETL\TLio.Extensions.ETL.csproj" />
    <ProjectReference Include="..\TLio.Extensions.Looping\TLio.Extensions.Looping.csproj" />

  </ItemGroup>

</Project>
